export const parishData = {
  name: "Paróquia Nossa Senhora do Carmo - Paraopeba",
  heroTitle: "Paróquia Nossa Senhora do Carmo - Paraopeba",
  heroText:
    "Informações da paróquia, secretaria, clero e comunidades da Diocese de Sete Lagoas.",
  celebrationsNote: "Confira nossos principais horários ativos.",
  massTimes: [
    { id: "m1", day: "1° Sexta", time: "19:30", location: "Matriz" },
    { id: "m2", day: "Sábado", time: "19:30", location: "Matriz" },
    { id: "m3", day: "Domingo", time: "07:30 e 19:30", location: "Matriz" },
    { id: "m4", day: "3° Domingo", time: "11:00", location: "Igreja Bom Jesus - Embiriçu" },
    { id: "m5", day: "1° e 3° Quarta do mês", time: "19:30", location: "Igreja Divino Espírito Santo" },
    { id: "m6", day: "4° Sábado", time: "16:00", location: "Igreja Jesus Misericordioso - Aguada" },
    { id: "m7", day: "3° quarta do mês", time: "18:00", location: "Igreja Nossa Senhora Aparecida - Canabrava" },
    { id: "m8", day: "1° Sábado do mês", time: "07:00", location: "Igreja Nossa Senhora do Rosário" },
    { id: "m9", day: "1° e 3° Quinta do mês", time: "06:00", location: "Igreja Nossa Senhora do Rosário" },
    { id: "m10", day: "1° Quinta do Mês", time: "19:30", location: "Igreja Nossa Senhora do Rosário - Pontinha" },
    { id: "m11", day: "Sábado", time: "18:00", location: "Capela Sagrado Coração de Jesus" },
    { id: "m12", day: "3° e 4° Quarta do mês", time: "19:30", location: "Igreja Santa Catarina de Sena" },
    { id: "m13", day: "5° domingo", time: "11:00", location: "Igreja Santa Maria" },
    { id: "m14", day: "Sexta", time: "19:30", location: "Igreja São Benedito" },
    { id: "m15", day: "3° Sexta", time: "19:30", location: "Igreja São Geraldo - Picada" },
    { id: "m16", day: "3° domingo", time: "11:00", location: "Igreja São José - Caboclo" },
    { id: "m17", day: "Dia 28", time: "19:30", location: "Igreja São Judas Tadeu" },
    { id: "m18", day: "Domingo", time: "09:00", location: "Igreja São Judas Tadeu" },
    { id: "m19", day: "2° Domingo do mês", time: "11:00", location: "Igreja Nossa Senhora das Dores - Retiro" },
    { id: "m20", day: "Quarta", time: "06:00", location: "Igreja Nossa Senhora da Piedade" },
    { id: "m21", day: "Domingo", time: "18:00", location: "Igreja Nossa Senhora da Piedade" },
    { id: "m22", day: "2° Sábado", time: "16:00", location: "Mucambo" },
  ],
  forania: "Nossa Senhora da Abadia",
  foundedYear: "1840",
  officeHours: "Segunda a Sexta: 08h às 12h e 13h às 17h",
  phone: "(31) 3714-1018",
  email: "paroquiaparaopeba@diocesedesetelagoas.com.br",
  secretary: "Maria Clara Gonçalves",
  address: "Praça Caetano Mascarenhas, 480, Centro",
  zipCode: "35774-000",
  clergy: [
    "Rafael Lucas Bastos Ribeiro (Pe.) - Administrador",
    "Roberto Vicente Leite (Vigário)",
  ],
  communitiesShort:
    "Comunidades: Matriz, Bom Jesus, Divino Espírito Santo, Jesus Misericordioso, N. Sra. Aparecida, N. Sra. do Rosário, Sagrado Coração, Santa Catarina, Santa Maria, São Benedito, São Geraldo, São José, São Judas Tadeu, N. Sra. das Dores, N. Sra. da Piedade e Mucambo.",
  notices: [
    "Acompanhe as celebrações e comunicados pela página oficial.",
    "Horários de missas podem sofrer ajustes em datas especiais.",
    "Para atendimento, use telefone ou WhatsApp da secretaria.",
  ],
  links: {
    diocesePage:
      "https://diocesedesetelagoas.com.br/paroquias/paroquia-nossa-senhora-do-carmo-paraopeba/",
    instagramProfile: "https://www.instagram.com/paroquiansra.docarmo/",
    instagramPost: "https://www.instagram.com/p/DWjnbvTEmNs/embed/",
    phoneHref: "tel:+553137141018",
    whatsapp: "https://wa.me/553137141018",
    mapEmbed:
      "https://www.google.com/maps?q=Pra%C3%A7a%20Caetano%20Mascarenhas%2C%20480%2C%20Paraopeba&output=embed",
  },
};
